#' @title `statsurv`: A package for developing and performing statistical surveillance
#'
#' @description Statistical surveillance is any sort of systematic, ongoing analysis aimed at
#'   detecting changes in outcomes as they occur.  If the amount of data reported is large or if
#'   there is significant natural variability in the rate of case events, statistical techniques can
#'   be extremely helpful in determining when a change in the number of events is important, and
#'   when it is merely noise.  The `statsurv` package is designed to help with both designing a
#'   statistical surveillance system and implementing it for routine use. One key part of this is
#'   making it easy to apply statistical surveillance to varying "windows" of data, to mimic of the
#'   process of routinely implementing a surveillance technique over time. This allows the
#'   performance of different statistical surveillance methods to be compared and evaluated.
#'
#'@section Overview:
#'   The `statsurv` package is designed for both performing statistical surveillance and for
#'   developing and evaluating those statistical surveillance methods. Typically, to conduct
#'   statistical surveillance, we need to collect and aggregate measurements of the variable of
#'   interest, and compare those measurements to a baseline estimate, typically generated by a
#'   model. This process is then repeated as additional measurements are collected over time.
#'
#'   The functions in the package fall into 5 main categories:
#'   \enumerate{
#'    \item Functions for preparing data for analysis
#'    \item Functions making it easier to generate predictions from models
#'    \item Functions for comparing outcomes with baseline estimates (scan statistic functions)
#'    \item Functions used to generate reports or summaries of the surveillance outcomes
#'    \item Functions for applying all the previous functions of varying data windows
#'}
#'
#' When developing a statistical surveillance system from scratch, generally the first steps will be
#' to collect and analyze the data, compare it to a model, and run it through a scan statistic to
#' generate results. The first four categories of functions are all used in this process. Then, the
#' process must be repeated over varying data windows to see how the system would have performed if
#' it had been in routine use since data collection began. Only then can the performance of the
#' system, including the average time to detect a simulated cluster and the average rate of false
#' alarms, be evaluated.
#'
#'@section Preparing data for analysis:
#' #### Key functions:
#'    \itemize{
#'    \item \code{\link{validate_spacetime_data}}
#'    \item \code{\link{pad_spacetime_data}}
#'    \item \code{\link{calculate_surveillance_residuals}}
#'    \item \code{\link{collapse_all}}
#'    \item \code{\link{create_zones}}
#'    \item \code{\link{prepare_training_data}}
#'    \item \code{\link{pivot_for_scan}}
#'    }
#'
#'@section Generating model predictions:
#' #### Key functions:
#' \itemize{
#'   \item \code{\link{extract_yhat}}
#'   \item \code{\link{arima_tidy}}
#'   \item \code{\link{glance_inla}}
#'   \item \code{\link{tidy_inla}}
#' }
#'
#' @section Alarm functions:
#' #### Key functions:
#' \itemize{
#'   \item \code{\link{parallel_cusum_gaussian}}
#'   \item \code{\link{parallel_cusum_gaussian2}}
#'   \item \code{\link{parallel_cusum_poisson}}
#'   \item \code{\link{parallel_cusum_poisson2}}
#'   \item \code{\link{parallel_shewhart_gaussian}}
#'   \item \code{\link{parallel_shewhart_gaussian2}}
#'   \item \code{\link{scan_eb_negbin_fast}}
#'   \item \code{\link{scan_eb_negbin_fast2}}
#'   \item \code{\link{scan_eb_poisson_fast}}
#'   \item \code{\link{scan_eb_poisson_fast2}}
#'   \item \code{\link{scan_cusum_poisson}}
#'   \item \code{\link{scan_bayes_negbin2}}
#'   \item \code{\link{scan_pb_poisson2}}
#'   \item \code{\link{scan_eb_poisson2}}
#'   \item \code{\link{scan_eb_zip2}}
#'   \item \code{\link{scan_permutation2}}
#'   \item \code{\link{scan_eb_negbin2}}
#'   \item \code{\link{scan_bayes_negbin2}}
#'   \item \code{\link{scan_cusum_poisson}}
#'   \item \code{\link{scan_bayes_negbin2}}
#' }

#'
#' @section Interpreting the results:
#' #### Key functions:
#' \itemize{
#' \item \code{\link{report_top_clusters}}
#' \item \code{\link{remove_overlapping_clusters}}
#' }
#'
#'
#' @section Repeating the analysis over time:
#' #### Key functions:
#' \itemize{
#' \item \code{\link{rowmute}}
#' \item \code{\link{window_idtime}}
#' \item \code{\link{prepare_training_data}}
#' }
#'
#'
#' @docType package
#' @name statsurv
#' @md
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @importFrom rlang .env
NULL

## quiets concerns of R CMD check re: the .'s that appear in pipelines
if (getRversion() >= "2.15.1")  utils::globalVariables(c("."))
